name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: v14.2.0
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check if release already exists
      id: release_exists
      uses: ./.github/actions/release-exists-action
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.NODE_VERSION }}
    - if: steps.release_exists.outputs.exists == false
      name: Build Node.js
      uses: ./.github/actions/build-node-action
      with:
        node_version: ${{ env.NODE_VERSION }}
    - if: steps.release_exists.outputs.exists == false
      name: List directory contents
      run: |
        ls -l
        ls -l node-${{ env.NODE_VERSION }}/
    - if: steps.release_exists.outputs.exists == false
      name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.NODE_VERSION }}
        release_name: Node.js ${{ env.NODE_VERSION }}
        body: Node.js ${{ env.NODE_VERSION }} suitable for use with CentOS 6
        draft: false
        prerelease: false
    - if: steps.release_exists.outputs.exists == false
      name: Upload .tar.gz
      id: upload-release-asset-xz
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./node-${{ env.NODE_VERSION }}/node-${{ env.NODE_VERSION }}-linux-x64.tar.xz
        asset_name: node-${{ env.NODE_VERSION }}-linux-x64.tar.xz
        asset_content_type: application/x-xz
    - if: steps.release_exists.outputs.exists == false
      name: Upload .tar.gz
      id: upload-release-asset-gz
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./node-${{ env.NODE_VERSION }}/node-${{ env.NODE_VERSION }}-linux-x64.tar.gz
        asset_name: node-${{ env.NODE_VERSION }}-linux-x64.tar.gz
        asset_content_type: application/gzip
    - if: steps.release_exists.outputs.exists == false
      name: Upload SHASUMS256.txt
      id: upload-release-asset-shasums
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./node-${{ env.NODE_VERSION }}/SHASUMS256.txt
        asset_name: SHASUMS256.txt
        asset_content_type: text/plain
